GET http://localhost:8080/api/index/
###
GET http://localhost:8080/api/category/6/
###
GET http://localhost:8080/api/stores/17/
###
GET http://localhost:8080/api/team/39/

###
POST http://localhost:8080/api/categories/store/add/
Content-Type: application/json

{
"name":"Test",
  "phoneNumber": "Test",
  "address": "Test",
  "website": "Test",
  "storeHours": "Test",
  "image": "Test",
  "description": "Test",
  "productList": "Test",
  "category": "category1"
}