GET http://localhost:8080/api/index/

###
GET http://localhost:8080/api/category/3/

###
GET http://localhost:8080/api/stores/23/

###
GET http://localhost:8080/api/team/39/

###
GET http://localhost:8080/api/store/random/

###
POST http://localhost:8080/api/categories/store/add/
Content-Type: application/json

{
  "name": "Test",
  "phoneNumber": "Test",
  "address": "Test",
  "website": "Test",
  "storeHours": "Test",
  "image": "Test",
  "description": "Test",
  "productList": "Test",
  "category": "category1"
}

###
PATCH http://localhost:8080/api/stores/38/update-store/
Content-Type: application/json

{
  "name": "Test1",
  "phoneNumber": "Test1",
  "address": "Test1",
  "website": "Test1",
  "storeHours": "Test1",
  "image": "Test1",
  "description": "Test1",
  "productList": "Test1",
  "category": "category1"
}
